import re

PATTERN = re.compile(
    r"(?P<side>Short|Long)\s*Liquidated.*?"
    r"(?:Symbol:|Asset:)?\s*"
    r"(?P<symbol>(?!Symbol|Asset)[A-Z0-9/]+).*?"
    r"(?P<label>Amount|Value|Size):\s*\$?(?P<amount>[\d,.]+)(?P<unit>[KMB]?)",
    re.IGNORECASE | re.DOTALL
)

def parse_and_reform_message(raw_text):
    """Parse liquidation message and transform into signal alert."""
    match = PATTERN.search(raw_text)
    if not match:
        return None

    data = match.groupdict()
    
    try:
        amount_str = data['amount'].replace(',', '')
        multiplier = 1
        unit = data.get('unit', '').upper()
        
        if unit == 'K': multiplier = 1000
        elif unit == 'M': multiplier = 1000000
        elif unit == 'B': multiplier = 1000000000
        
        real_amount = float(amount_str) * multiplier
    except ValueError:
        return None

    if real_amount < 10000:
        return None 

    side = data['side'].title()
    symbol = data['symbol'].replace('/', '')
    
    if side == "Short":
        emoji = "🟢"
        title = "POTENTIAL SHORT SQUEEZE"
        action = "Buy Pressure Increasing"
    else:
        emoji = "🔴"
        title = "LONG LIQUIDATION CASCADE"
        action = "Sell Pressure Increasing"

    new_message = (
        f"{emoji} **{title}**\n\n"
        f"🪙 **Asset:** #{symbol}\n"
        f"📉 **Liq Size:** ${real_amount:,.0f}\n"
        f"📊 **Insight:** {action}\n"
        f"__Generated by SignalFilterBot__"
    )
    
    return new_message
